### ISSUE TITLE
Input/Output Error

### ISSUE THREAD

**Issue by inodb** [mskcc/HPC-UserGroup#2]
Pretty tricky to reproduce this error. But here for instance:
```
/home/limr/share/data/mucinous/rnaseq/modules $ git pull
error: cannot open .git/FETCH_HEAD: Input/output error
```
It's not only happening with git pull but with all kinds of scripts

**Comment by nhgirija** [comment]
Where are you pulling from which server exactly

Thanks
Neeraj

**Comment by inodb** [comment]
s01

**Comment by inodb** [comment]
It's the same on saba2, unagi, luna and I'm sure some other nodes

**Comment by nhgirija** [comment]
Can you try again from luna.mskcc.org

**Comment by inodb** [comment]
Still the same error

**Comment by inodb** [comment]
Looks like this has mysteriously been solved. At least for now.
