### ISSUE TITLE
unagi is out of /tmp space

### ISSUE THREAD

**Issue by raylim** [mskcc/HPC-UserGroup#4]
For various interactive tools that I run, it's not always clear how to set the tmp dir, and it would be helpful if it was cleaned up.

**Comment by juanperin** [comment]
If you’re on Unagi and directly using the system within the same shell, (ie.. not qsubbing), you should be able to reset your temp directory for such applications by exporting 

> export $TMPDIR=XXX

**Comment by raylim** [comment]
Yes, I tried that, but it wasn't working for a particular tool.  Regardless, I managed to contact a user to resolve this.
