### ISSUE TITLE
Trouble accessing bam files (via saba2, e01-e06 nodes, etc.) in ~limr/share/data/mucinous/rnaseq/bam/

### ISSUE THREAD

**Issue by raylim** [mskcc/HPC-UserGroup#6]
`ls` appears to hang indefinitely in `~limr/share/data/mucinous/rnaseq/bam/`.

**Comment by nhgirija** [comment]
Looking.

**Comment by nhgirija** [comment]
seems like the folder is very big and very busy.

**Comment by raylim** [comment]
I'm running a process on e06 (Integrate) that is using a bam file from this dir.  Would that be why?

**Comment by nhgirija** [comment]
[root@saba2 rnaseq]# fuser -cu bam/
bam/:                 1717(defilipm)  1718(bermans)  3425ce(bermans)  3427c(bermans)  3428ce(bermans)  4008c(josephv)  4009c(josephv)  4616c(bermans)  4617ce(bermans)  4743c(bermans)  4746ce(bermans)  4793c(debruiji)  4944ce(bermans)  5016c(bermans)  5017ce(bermans)  5300c(limr)  5686c(limr)  6312c(huw)  6593c(huw)  6770c(bermans)  7080c(schizasm)  7152c(josephv)  7306c(josephv)  7307c(josephv)  7308c(josephv)  8789c(josephv)  8872(defilipm)  8945c(limr)  9721c(bermans) 10507ce(bermans) 11283c(bermans) 11682ce(bermans) 12397c(limr) 13386(burkek) 13393c(burkek) 13589ce(limr) 13592c(limr) 13593ce(limr) 13595c(limr) 13597ce(limr) 14307c(josephv) 14736c(bermans) 17540(burkek) 17595c(limr) 17748c(bermans) 17809ce(bermans) 18036c(bermans) 18206c(bermans) 19247c(burkek) 19738(defilipm) 20358c(huw) 20478c(bermans) 20815ce(limr) 20938cm(josephv) 20989c(ngk1) 20990c(ngk1) 22446ce(bermans) 22835ce(bermans) 22885(limr) 23285c(josephv) 23422c(josephv) 23729c(bermans) 24946ce(limr) 25182c(josephv) 25201(defilipm) 26529m(bermans) 26530c(bermans) 26891c(josephv) 27302c(bermans) 27547c(huw) 27622c(bosep) 27740c(bosep) 27794c(limr) 27973c(bosep) 28020c(josephv) 28021c(josephv) 28634c(ngk1) 28635c(ngk1) 28641ce(ngk1) 28819c(root) 29019c(liy) 29212c(ngk1) 29213c(ngk1) 29225ce(ngk1) 29234m(limr) 29247c(limr) 29298c(limr) 29331c(ngk1) 29332c(ngk1) 29338ce(ngk1) 29520c(burkek) 29521c(burkek) 29522c(burkek) 29666c(root) 29870c(root) 29940c(bermans) 30000c(bosep) 30077c(ngk1) 30157c(limr) 30314c(root) 30451c(root)

**Comment by nhgirija** [comment]
Also the folder seem to have a very large number of files. I ran a find that completed in over 30 mins.

**Comment by raylim** [comment]
It's probably due to the temp files from name sorting the bam files.  `defilipm` left our lab a while back.  Could you kill her processes and delete her crontab?

**Comment by nhgirija** [comment]
I disabled her cron and killed her processes. There is still 17M files in that directory it will be slow to ridiculously slow
[root@saba2 rnaseq]# ps -ef |grep defilipm
root     32347 32209  0 16:34 pts/60   00:00:00 grep defilipm

**Comment by raylim** [comment]
Okay thanks. I'll try to remove the files.  There are a lot of files with a .tmp suffix?

**Comment by nhgirija** [comment]
Yes  Here is a example. Please let us know if we can do anything to help.

solisi-1# find /ifs/nl/saba/e63data/reis-filho/data/mucinous/rnaseq/bam 
/ifs/nl/saba/e63data/reis-filho/data/mucinous/rnaseq/bam
/ifs/nl/saba/e63data/reis-filho/data/mucinous/rnaseq/bam/MCM6.bam.tmp.132681.bam
/ifs/nl/saba/e63data/reis-filho/data/mucinous/rnaseq/bam/MCM10.bam.tmp.141389.bam
/ifs/nl/saba/e63data/reis-filho/data/mucinous/rnaseq/bam/MCM30.bam.tmp.651038.bam
/ifs/nl/saba/e63data/reis-filho/data/mucinous/rnaseq/bam/MCM12.bam.tmp.843565.bam
/ifs/nl/saba/e63data/reis-filho/data/mucinous/rnaseq/bam/MCM6.bam.tmp.1007240.bam
